pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image'
                sh 'docker build -t task-manager:ci -f docker/Dockerfile .'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
